[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add dependencies here as we build
# e.g., tokio = { version = "1", features = ["full"] }
# e.g., serde = { version = "1.0", features = ["derive"] }